business_time:
  beginning_of_workday: 9:00 am
  end_of_workday: 5:00 pm
  holidays:
    - Jan 01, 2018
    - July 3rd, 2017
    - September 4th, 2017
    - December 25th, 2017
    - December 26th, 2017
  work_week:
    - mon
    - tue
    - wed
    - thu
    - fri
